'use strict';
const KEY='englishMemoProgressV2',DAYS=[1,3,7,14,30,60,120],GAPS=[3,7,12],DAY=864e5;
const s={words:[],progress:{},queue:[],current:null,answered:false,passes:0,correct:0,errors:0};
const $=id=>document.getElementById(id),norm=x=>String(x??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().replace(/[.!?…]+$/g,'').replace(/\s+/g,' '),id=w=>`${norm(w.french)}__${norm(w.english)}`;
function p(w){return s.progress[id(w)]??=( {status:'new',level:0,step:0,success:0,errors:0,next:null} )}function save(){localStorage.setItem(KEY,JSON.stringify(s.progress))}function add(d,n){return new Date(d.getTime()+n*DAY)}function show(x){['home','game','result'].forEach(y=>$(y).hidden=y!==x)}
function renderStats(){let n=0,l=0,d=0,m=0,now=new Date();s.words.forEach(w=>{let q=p(w);if(q.status==='new')n++;else if(q.status==='learning')l++;else if(q.next&&new Date(q.next)<=now)d++;else if(q.level>=5)m++});$('stats').textContent=`À revoir : ${d} • Nouveaux : ${n} • En apprentissage : ${l} • Maîtrisés : ${m}`}
async function load(){try{s.progress=JSON.parse(localStorage.getItem(KEY)||'{}');let r=await fetch(`vocabulaire.json?v=${Date.now()}`),data=await r.json();s.words=data.map(w=>({...w,category:w.category||'Sans catégorie',french_answers:w.french_answers||[w.french],english_answers:w.english_answers||[w.english]}));let cats=['Toutes',...new Set(s.words.map(w=>w.category))];$('category').innerHTML=cats.map(x=>`<option>${x}</option>`).join('');$('status').textContent=`${s.words.length} mots disponibles`;$('start').disabled=false;renderStats()}catch(e){$('status').textContent=`Erreur : ${e.message}`}}
function priority(w){let q=p(w),now=new Date();if(q.status==='learning')return 1e5;if(q.next&&new Date(q.next)<=now)return 8e4;if(q.status==='new')return 5e4;return 1000-q.level}
function start(){let pool=$('category').value==='Toutes'?[...s.words]:s.words.filter(w=>w.category===$('category').value);pool=pool.map(w=>({w,r:Math.random()})).sort((a,b)=>priority(b.w)-priority(a.w)||a.r-b.r).map(x=>x.w);let z=$('size').value==='all'?pool.length:Math.min(+$('size').value,pool.length);s.queue=pool.slice(0,z).map(word=>({word}));s.passes=s.correct=s.errors=0;show('game');card()}
function later(item,gap){s.queue.splice(Math.min(gap,s.queue.length),0,item)}function expected(){let w=s.current.word;return $('direction').value==='fr-en'?w.english_answers:w.french_answers}
function card(){if(!s.queue.length)return finish();s.current=s.queue.shift();s.answered=false;let w=s.current.word,q=p(w),fr=$('direction').value==='fr-en';$('instruction').textContent=fr?'Traduis en anglais':'Traduis en français';$('prompt').textContent=fr?w.french:w.english;$('meta').textContent=`${w.category} • ${q.status==='new'?'Nouveau':q.status==='learning'?`Apprentissage ${q.step+1}/3`:`Niveau ${q.level}`}`;$('answer').value='';$('answer').disabled=false;$('form').hidden=false;$('next').hidden=true;$('feedback').textContent='';$('feedback').className='';$('counters').textContent=`Passages : ${s.passes} • Réussites : ${s.correct} • Erreurs : ${s.errors}`;setTimeout(()=>$('answer').focus(),30)}
function correct(item){let q=p(item.word),now=new Date();q.success++;if(q.status==='new'){q.status='learning';q.step=1;later(item,GAPS[0])}else if(q.status==='learning'){q.step++;if(q.step<3)later(item,GAPS[q.step-1]);else{q.status='review';q.level=Math.max(1,q.level);q.step=0;q.next=add(now,DAYS[q.level-1]).toISOString()}}else{q.level=Math.min(q.level+1,DAYS.length);q.next=add(now,DAYS[q.level-1]).toISOString()}}
function wrong(item){let q=p(item.word);q.errors++;q.status='learning';q.step=0;q.level=Math.max(0,q.level-1);q.next=null;later(item,2)}
$('form').addEventListener('submit',e=>{e.preventDefault();if(s.answered||!$('answer').value.trim())return;let a=expected().filter(Boolean),ok=a.some(x=>norm(x)===norm($('answer').value));s.answered=true;s.passes++;if(ok){s.correct++;correct(s.current)}else{s.errors++;wrong(s.current)}save();$('answer').disabled=true;$('form').hidden=true;$('next').hidden=false;$('feedback').className=ok?'good':'bad';$('feedback').textContent=ok?'✓ Bonne réponse.':`✕ Réponse : ${a.join(' ou ')}. Retour dans 2 cartes.`;$('counters').textContent=`Passages : ${s.passes} • Réussites : ${s.correct} • Erreurs : ${s.errors}`});
function finish(){let pct=s.passes?Math.round(100*s.correct/s.passes):0;$('percent').textContent=`${pct} %`;$('summary').textContent=`${s.passes} passages, ${s.correct} réussites, ${s.errors} erreurs.`;renderStats();show('result')}
$('start').onclick=start;$('next').onclick=card;$('quit').onclick=finish;$('homeButton').onclick=()=>show('home');document.addEventListener('keydown',e=>{if(e.key==='Enter'&&s.answered&&!$('game').hidden){e.preventDefault();card()}});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('service-worker.js'));load();
